apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: developer-requested
  labels:
spec:
  storageClassName: storageos
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
