apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: developer-requested-rep
  labels:
      storageos.com/replicas: "1" # ask for 1 replica of the data
spec:
  storageClassName: storageos
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
