apiVersion: v1
kind: Pod
metadata:
  name: pod-rep-enc-tap
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sleep"]
      args: [ "3600" ]
      volumeMounts:
        - mountPath: /mnt
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: developer-requested-rep-enc-tap
