aws ec2 create-launch-template \
          --launch-template-name chris-sademo-ondat-1disk \
          --version-description version1 \
          --launch-template-data '{"BlockDeviceMappings":[{"DeviceName":"/dev/sda","Ebs":{"VolumeSize":100,"VolumeType":"gp2","DeleteOnTermination":true}}]}'
```
```
{
    "LaunchTemplate": {
        "LaunchTemplateId": "lt-02145ec1905999167",
        "LaunchTemplateName": "chris-sademo-ondat-1disk",
        "CreateTime": "2021-11-19T13:41:24+00:00",
        "CreatedBy": "arn:aws:iam::499176610670:user/chris.milsted",
        "DefaultVersionNumber": 1,
        "LatestVersionNumber": 1
    }
}
```

```
aws ec2 modify-launch-template --launch-template-id "lt-06d043edaf960e254" --default-version "3" --region "eu-central-1"
```

#!/bin/bash
mkfs -t ext4 /dev/xvdb
mkdir -p /var/lib/storageos
mount /dev/xvdb /var/lib/storageos




kubectl apply -f- <<EOF
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: topsecret
 labels:
 app: storageos
provisioner: csi.storageos.com # CSI Driver
allowVolumeExpansion: true
parameters:
 storageos.com/replicas: "2" # 3 copies of Data, 1 Primary, 2 Replicas
 storageos.com/encryption: "true" # Enable encryption
 storageos.com/topology-aware: true # Enable TAP
 csi.storage.k8s.io/controller-expand-secret-name: csi-controller-expand-secret csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
 csi.storage.k8s.io/controller-publish-secret-name: csi-controller-publish-secret csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
 csi.storage.k8s.io/fstype: ext4
 csi.storage.k8s.io/node-publish-secret-name: csi-node-publish-secret
 csi.storage.k8s.io/node-publish-secret-namespace: kube-system
 csi.storage.k8s.io/provisioner-secret-name: csi-provisioner-secret
 csi.storage.k8s.io/provisioner-secret-namespace: kube-system
EOF

